spring:
    datasource:
        url: jdbc:postgresql://${DB_HOST:@localhost}:${DB_PORT:1521}/swe_db
        username: ${DB_USER:root}
        password: ${DB_PASSWORD:root}
    jpa:
        show-sql: true
        format-sql: true
        hibernate:
        ddl-auto: none
    properties:
        hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect