server.port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/swe_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: none
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:config/liquibase/master.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/SearchWithEase
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs