spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/swe_db
        username: postgres
        password: postgres
    jpa:
        show-sql: true
        format-sql: true
        hibernate:
            ddl-auto: none
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect